[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-args=-Map=bl602-loader.map",
  "-C", "link-args=--nmagic",
]

[build]
target = "riscv32imac-unknown-none-elf"
