[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-args=-Map=bl602-loader.map",
  "-C", "link-args=--nmagic",
  # We don't know where the flash loader will be
  # placed in memory, so we need to create
  # position independent code (pic).
  "-C", "relocation-model=pic",
]

[build]
target = "riscv32imac-unknown-none-elf"
